version: '3.1'

services:
  booksonline-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - psqldb
    volumes:
      - ".:/booksonline-api/src/app"
  psqldb:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mengingatMU513
      POSTGRES_DB: booksonline_db
